blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/cryptic-prophage/mauve-classroom/discussions
    about: Ask a question or start a discussion about using Mauve
